### ISSUE TITLE
Noti doesn't expand alias arguments

### ISSUE THREAD

**Issue by simioes** [variadico/noti#11] opened 2016-01-19 09:43 UTC
After installed, i tried with some created alias and it fails. If i run the command assigned to the alias it works as expected.

**Comment by variadico** [comment] 2016-01-26 04:00
Could you post more information about this? I wasn't able to reproduce this.

I set this in my `~/.zshrc`.
```
alias n="noti"
```
Then I ran `source ~/.zshrc`.

I was able to run `n -V alex` successfully.

**Comment by simioes** [comment] 2016-01-26 10:07
I am not talking about set "noti" as an alias. For example, in osx:

alias speak_hello=' say "hello"'

noti speak_hello give an error. No detailed information, but the command in alias does not run.
Try that.

**Comment by variadico** [comment] 2016-01-31 23:07
Ah, yes.

In v2, you now see more information.

![image](https://cloud.githubusercontent.com/assets/4296393/12705782/c602b6fa-c82b-11e5-99d7-e198f3ac9be8.png)

Currently, `noti` assumes `utility` is an executable in your `$PATH`. It didn't evaluate your alias. Interestingly, the `time` command _does_ evaluate aliases, so, yes: this is a bug.

**Comment by variadico** [comment] 2016-02-06 07:47
Wait. I just realized `time` isn't `/usr/bin/time` in my shell. Running `/usr/bin/time speak_hello` also results in the same behavior as `noti`. I'm guessing the reason it worked before was because Zsh knew how to expand the alias when it ran its version of `time`.

Getting this behavior right seems tricky—and doing it in a way that works across different shells seems even more difficult.

Technically, you can get this to work in bash, version 3.2.57, like this.
```
shopt -s expand_aliases
alias speak_hello='say "hola"'
noti $(speak_hello)
```

**Comment by variadico** [comment] 2016-09-02 02:39
Hi, @vyasgiridhar, @chmaynard, and @simioes.

I think I might have finally found a solution to this, that's not too crazy. (No regexp.)

```
cd github.com/variadico/noti/cmd/noti
git fetch --all
git checkout expand-alias
go install
```

Then try running `noti` on some shell alias.

```
noti speak_hello
```

Can anyone else verify this works? I tried this on macOS Sierra with ZSH. It would be awesome if someone could test on other platforms and shells. ✌️ 

Thanks!!

**Comment by vyasgiridhar** [comment] 2016-09-02 05:32
```
which: no pacupg in (/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/go/bin:/home/vyas/stunts/go/bin)
```
```which``` does not seem to look at aliases but rather in all the variables.
Running bash on Arch Linux here.

**Comment by vyasgiridhar** [comment] 2016-09-02 13:48
It works on bash in Arch linux. :+1:

**Comment by vyasgiridhar** [comment] 2016-09-02 16:00
But can you change 
```
cmd := exec.Command(shell, "-l", "-i", "-c", "which "+a)
```
using 
```
cmd := exec.Command(shell, "-l", "-i", "-c",a)

```
would directly spawn the alias process.

**Comment by variadico** [comment] 2016-09-08 03:13
Merged the alias change to dev, https://github.com/variadico/noti/commit/159829289b8d44d1754019579877772b1a075d28.

@vyasgiridhar, I liked your change, but I kept it the way I had it because executing the alias in the subshell caused arguments passed to aliases to be escaped.

```
$ which findhere 
findhere: aliased to find . -iname
$ noti findhere '*.go' # <- Expanding
$ noti findhere '\*.go' # <- Executing directly
```

Maybe we can optimize this later.

**Closed by variadico** 2016-09-08 03:13 UTC
Labels: enhancement
