### ISSUE TITLE
Run noti in Docker

### ISSUE THREAD

**Issue by pascalandy** [variadico/noti#62] opened 2017-09-30 20:58 UTC
I'm about to push a PR for running noti in a docker container.
It's working but I'm looking to make the image leaner. 

So far it looks like this project is depending on `notify-osd`.

### Before notify-osd

The base image for debian:jessie-slim is 87Mo. 

<img width="793" alt="screen shot 2017-09-30 at 4 36 05 pm" src="https://user-images.githubusercontent.com/6694151/31049296-7418e9b0-a5fe-11e7-8fa1-897bae6d1451.png">

### After notify-osd

Now it's 230 Mo

<img width="795" alt="screen shot 2017-09-30 at 4 42 19 pm" src="https://user-images.githubusercontent.com/6694151/31049298-76cd2c98-a5fe-11e7-8acc-1c4acedc0762.png">

### My question
1) I'm curious to know if some folks knows a smaller package than `notify-osd` ?
2) I would prefer to build on alpine but I can't find a way to install `notify-osd` on it.

### dockerfile (multi-stage)

```
# stage build
### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
FROM golang as stage

RUN apt-get update -y && \
	apt-get install -y \
	curl bash git wget ca-certificates

RUN go get -u github.com/variadico/noti/cmd/noti

WORKDIR /go


# final build
### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
FROM debian:jessie-slim

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p /go && \
	mkdir -p "$GOPATH/src" "$GOPATH/bin" && \
	chmod -R 777 "$GOPATH"

RUN apt-get update -y && \
	apt-get install -y \
	ca-certificates \
	notify-osd \
	&& \
	apt-get -y autoclean -y && \
	apt-get -y autoremove && \
	apt-get purge && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR $GOPATH

COPY --from=stage /go/bin /go/bin
```

### docker run

```
SLACK_TOKEN_CRON="xowEF34TQ345TY-Q345GQ3AREBERG3QA4-5TYGAERBAE5Y24-76"
ENV_DATE_SEC="$(date +%Y-%m-%d_%HH%M_%S)"
IMG_test="devmtl/noti:edge_2017-09-30_16H10"
\
echo;
docker run --rm \
--name noti \
-e NOTI_MESSAGE="Test from noti $ENV_DATE_SEC" \
-e SLACK_CHANNEL="cron" \
-e SLACK_TOKEN_CRON="$SLACK_TOKEN_CRON" \
"$IMG_test" \
sh -c \
'NOTI_SLACK_TOK="$SLACK_TOKEN_CRON" \
NOTI_SLACK_DEST="$SLACK_CHANNEL" \
noti -k -m "$NOTI_MESSAGE"'; echo;
```

Cheers!

**Comment by pascalandy** [comment] 2017-10-01 14:51
I don't know exactly why noti is complaining about:
`Install 'notify-send' and try again` when I don't install this package. But to notify slack from my container **it works!**

### image size

<img width="1214" alt="screen shot 2017-10-01 at 10 49 42 am" src="https://user-images.githubusercontent.com/6694151/31055793-441c3f62-a696-11e7-88fc-97ac4074b2d3.png">

### dockerbuild multi (debian)

```
# stage build
### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
FROM golang as stage

RUN apt-get update -y && \
	apt-get install -y \
	curl bash git wget ca-certificates

RUN go get -u github.com/variadico/noti/cmd/noti

WORKDIR /go


# final build
# it won't have go's libraries
# there is a dependencie on notify-osd
### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
FROM debian:jessie-slim

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

WORKDIR $GOPATH

RUN mkdir -p /go && \
	mkdir -p "$GOPATH/src" "$GOPATH/bin" && \
	chmod -R 777 "$GOPATH"

RUN apt-get update -y && \
	apt-get install -y \
	ca-certificates \
	#notify-osd \
	&& \
	apt-get -y autoclean -y && \
	apt-get -y autoremove && \
	apt-get purge && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=stage /go/bin /go/bin
```

### dockerbuild multi (alpine)

```
# stage build
### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
FROM golang:alpine as stage

RUN apk update && apk upgrade && apk add git ca-certificates && rm -rf /var/cache/apk/*

RUN go get -u github.com/variadico/noti/cmd/noti

WORKDIR /go


# final build
# it won't have go's libraries
# I bypassed notify-osd even if the system complains about installing it
### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
FROM alpine:3.6

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

WORKDIR $GOPATH

RUN mkdir -p /go && \
	mkdir -p "$GOPATH/src" "$GOPATH/bin" && \
	chmod -R 777 "$GOPATH"

RUN apk update && apk upgrade && apk add ca-certificates && rm -rf /var/cache/apk/*

COPY --from=stage /go/bin /go/bin
```

### challenge

To push a PR, my challenge is that bypassing `notify-send` works for my use case but probably won't work for everyone. 228MB vs 14.4MB

I leave this open for discussion. Enjoy!

**Comment by variadico** [comment] 2017-12-23 08:29
Noti 2.7's behavior here is weird.

```
$ noti -k 
```

Will actually fire 2 notifications. 1 banner and 1 Slack.

If you just want Slack, then you have to explicitly disable the banner notification.

```
$ noti -k -b=0
```

I think this way you can avoid installing `notify-osd`. I thought this was a bug until I started looking at it. Technically, this is working as intended, but the current behavior is confusing.

**Comment by variadico** [comment] 2018-01-06 09:17
Closing this. With noti 3.0.0 this appears to work now.

**Closed by variadico** 2018-01-06 09:17 UTC
Labels: bug
